# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Rabbot.io
email: katotop@gmail.com
description: >
  Be Awesome!
favicon: "/favicon.ico"
logo: "assets/images/rabbot-320x320.png"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rabbot.io" # the base hostname & protocol for your site
paginate:	1 # The number of posts to show per page on your homepage
paginate_path: "/blog/page:num"

name: 'katopz'
bio: >
  Design Develop Debug Deploy.
author_image: "/assets/images/author.jpg"
twitter_username: katopz
github_username:  katopz

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate
  
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - webpack.config.js
  - webpack.hot.config.js
  - npm-debug.log
  - Procfile
  - Procfile.dev
  - node_modules
  - glupfile.js
  - package.json